---
- hosts: localhost
  connection: local
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "raju-aws-key"
        instances_type: t2.micro
        security_group: default
        region: ap-south-1
        aws_access_key: "{{ec2_access_key}}" # define from vault
        aws_secret_key: "{{ec2_secret_key}}" # define from vault
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
      loop:
        - { image: "ami-0123fhofihihew", name: "manage-node-1" }
        - { image: "ami-024jkdkjiofcei", name: "manage-node-2" }
        - { image: "ami-0gi4jkafhofihi", name: "manage-node-3" }